### ISSUE TITLE
spf2ip fails on certain domains.

### ISSUE THREAD

**Issue by hboetes** [nathandines/SPF2IP#4] opened 2020-12-30 18:22 UTC
For example:
```
# SPF2IP --domain linkedin.com --ip-version 4
Traceback (most recent call last):
  File "/usr/local/bin/SPF2IP", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/SPF2IP.py", line 169, in main
    for ip in lookup.IPArray(args.ip_version):
  File "/usr/local/lib/python3.6/dist-packages/SPF2IP.py", line 70, in IPArray
    NewIncludes = self.FindIncludes(domain)
  File "/usr/local/lib/python3.6/dist-packages/SPF2IP.py", line 84, in FindIncludes
    entries = self.GetSPFArray(domain)
  File "/usr/local/lib/python3.6/dist-packages/SPF2IP.py", line 94, in GetSPFArray
    results = dns_request_unicode(domain,'TXT')
  File "/usr/local/lib/python3.6/dist-packages/SPF2IP.py", line 17, in dns_request_unicode
    result = dns.resolver.query(hostname,record_type,*args,**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dns/resolver.py", line 1223, in query
    True)
  File "/usr/local/lib/python3.6/dist-packages/dns/resolver.py", line 1207, in resolve
    lifetime, search)
  File "/usr/local/lib/python3.6/dist-packages/dns/resolver.py", line 1040, in resolve
    (nameserver, port, tcp, backoff) = resolution.next_nameserver()
  File "/usr/local/lib/python3.6/dist-packages/dns/resolver.py", line 598, in next_nameserver
    raise NoNameservers(request=self.request, errors=self.errors)
dns.resolver.NoNameservers: All nameservers failed to answer the query linkedin.com. IN TXT: Server 10.10.10.11 UDP port 53 answered ; Server 10.10.10.11 TCP port 53 answered [Errno 111] Connection refused; Server 10.10.10.12 UDP port 53 answered ; Server 10.10.10.12 TCP port 53 answered [Errno 111] Connection refused
```
I somewhat suspect this problem might be caused by the unbound nameservers that don't like all these recursions, but I checked the config and rate limiting is disabled. So my question is, can you repeat this or is this a local problem?

**Comment by hboetes** [comment] 2020-12-30 19:44
I've tried the same script in another domain and there it works, so all I can ask for is a more helpful error message.

**Comment by nathandines** [comment] 2021-01-06 09:24
I didn't experience any error when running SPF2IP against linkedin.com. It looks to me like the error is related to a failure at your local name servers.

I'd suggest looking into your DNS servers and seeing why they might be failing. It would be worth testing changing your name servers to some public ones and seeing how you go with those (e.g. 1.1.1.1, 1.0.0.1, 8.8.8.8, 8.8.4.4)

I think the error message provided by dnspython is sufficient, and reflects the cause of the failure appropriately, so I'm not inclined to override it.

Closing this issue, as I don't feel there is anything to be done for it.

**Closed as completed by nathandines** 2021-01-06 09:24 UTC
